### ISSUE TITLE
ModuleNotFoundError: No module named 'helpers'

### ISSUE THREAD

**Issue by o-lucky-o** [brdav/refign#1]
I run this command in a teminal :
python tools/run.py test --config configs/cityscapes_acdc/refign_daformer.yaml --ckpt_path pretrain_models/refign_daformer_acdc.ckpt --trainer.gpus 1

but there is a error:
Traceback (most recent call last):
  File "tools/run.py", line 2, in <module>
    from helpers.cli import ConditioningLightningCLI
ModuleNotFoundError: No module named 'helpers'

here is my folder：
![Snipaste_2022-11-11_16-58-41](https://user-images.githubusercontent.com/55443787/201304324-762ef19c-44e8-4858-9288-0357cf0673bf.png)

how to solve the problem?

**Comment by brdav** [comment]
Hi, make sure to install the listed requirements, in particular refign itself via "pip install -e ."

**Comment by o-lucky-o** [comment]
Thanks for your help.
I forget to run the command :   pip install -e .
