### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by JCongLang** [brdav/refign#11]
This is really an outstanding job！
Can you provide pretrained models on Cityscapes? 
I didn't find it. thank you

**Comment by brdav** [comment]
Thank you! You can find the pretrained Cityscapes model under the link in the code here:
https://github.com/brdav/refign/blob/53a54219d01ea45b0f3cfef8b38abe1aef295d6a/models/backbones/mix_transformer.py#LL26C77-L26C77
I took the model from the original SegFormer repo.

**Comment by JCongLang** [comment]
Sorry to bother you, the link to the pretrained Cityscapes model is showing a 404 error. Could you please provide it again?
![image](https://github.com/brdav/refign/assets/108472371/67529ccd-24d0-4c1f-a61b-e68f0f0309ae)

**Comment by brdav** [comment]
I updated the links a while ago, you can access the Cityscapes model through the official SegFormer repo (see updated README).
