### ISSUE TITLE
Pretrained model downloading problem

### ISSUE THREAD

**Issue by Jumponthemoon** [brdav/refign#14]
Hi, 
First of all, appreciate the great work!
But when I run the training code and follow the steps in README.md, it gives the error:
![image](https://github.com/brdav/refign/assets/39290403/f0fc6509-d39e-4768-bffe-0ab6a1338315)

I'm not sure where the downloading function is called and where I can put the correct model URL. 

Please help me out, thanks!

**Comment by Jumponthemoon** [comment]
![image](https://github.com/brdav/refign/assets/39290403/6e875209-29e4-46a9-89cf-cd6908ecc448)

**Comment by brdav** [comment]
Hello, 
just save this model: 
`https://data.vision.ee.ethz.ch/brdavid/refign/uawarpc_megadepth.ckpt`
to 
`./pretrained_models/`
It is not automatically downloaded.
