### ISSUE TITLE
Questions about environment Settings

### ISSUE THREAD

**Issue by RyanQR** [brdav/refign#15]
Hello, after I set the environment according to README, the following problems appear in the running experiment. Is there any solution?
Error building extension 'correlation'
<img width="1317" alt="image" src="https://github.com/brdav/refign/assets/82513070/cbd3448d-c1a6-4d74-bd01-be9466f62c3e">

**Comment by brdav** [comment]
Hi, can you try pre-installing the local correlation extension instead?

https://github.com/brdav/refign#local-correlation

**Comment by RyanQR** [comment]
Thanks for your suggestion. It appears that using the command 'pip install spatial-correlation-sampler' does not successfully download the package directly. It seems there might be an issue with the package availability or compatibility.

**Comment by RyanQR** [comment]
> Hi, can you try pre-installing the local correlation extension instead?
> 
> https://github.com/brdav/refign#local-correlation

I find that cuda 11.0 does not support 8.6 but 11.1 does. So changing cuda to 11.1 should work.
