### ISSUE TITLE
Inquiry Regarding Submission Template for Test Dataset Ground Truth

### ISSUE THREAD

**Issue by cha-suyeon** [brdav/refign#16]
Hello, I'm suyeon.
I want to participate in the competition. I am facing a challenge related to the submission process, particularly concerning the test dataset ground truth.

Unfortunately, the provided test dataset lacks ground truth information, and I am unsure about the template format required for submission to the competition. Could you please provide guidance or share a template that aligns with the competition's requirements for submitting results for the test dataset?

I appreciate your time and assistance in this matter. 

If there are specific guidelines or templates available, your insights will be invaluable for ensuring a successful submission.

Thank you in advance for your help.

**Comment by brdav** [comment]
Hello,
we don't provide any submission benchmarks in this project, all benchmarks are third-party. See the README on how to create predictions, e.g. with
```
python tools/run.py predict --config configs/cityscapes_acdc/refign_hrda_star.yaml --ckpt_path /path/to/trained/model --trainer.gpus 1
```
