### ISSUE TITLE
About dataset bdd100k 

### ISSUE THREAD

**Issue by Carmanlst** [brdav/refign#17]
Hello, your work is very impressive. Does the bdd100k dataset require some processing? I didn't find the path in the data set that you provided in the project.I downloaded the red line data set.
![捕获](https://github.com/brdav/refign/assets/98247632/4d28ee46-5031-443c-b948-f908599de84b)
The file path you specified was not found:
![捕获](https://github.com/brdav/refign/assets/98247632/6b02a79a-c0da-4e4e-a078-673a8a8073fd)

**Comment by brdav** [comment]
Hello, the path should follow the structure of the BDD100K dataset outlined here: https://doc.bdd100k.com/download.html#semantic-segmentation
What do you mean by red line dataset? It seems there is a problem with the BDD100K host server, I cannot access https://bdd-data.berkeley.edu/ at the moment.

**Comment by Carmanlst** [comment]
I also can't access the BDD100K website, I have tried for many days, could you please provide a BDD100k data set? My email is 2955129368@qq.com. Thank you very much for your reply.

**Comment by brdav** [comment]
Unfortunately I can't share the data myself, sorry. My suggestion would be to try to contact the maintainers of the BDD100K dataset.
