### ISSUE TITLE
UAWarpC

### ISSUE THREAD

**Issue by scott-vsi** [brdav/refign#3]
Is it possible to use this [UAWarpC](https://github.com/brdav/refign#alignment-1) model in your [brdav/DenseMatching](https://github.com/brdav/DenseMatching) fork (sorry, I would have posted this issue in that repo, but I can't create an issue in a forked repo).

I tried loading it with a `PDCNet_vgg16` created like you create it in [train_UAWarpC_PDCNet_stage1.py](https://github.com/brdav/DenseMatching/blob/05bca868c3278e973800a9f93a03480d93d1aaa4/train_settings/UAWarpC/train_UAWarpC_PDCNet_stage1.py#L100) and then calling `network.set_inference_parameters` like in [model_selection.py](https://github.com/brdav/DenseMatching/blob/05bca868c3278e973800a9f93a03480d93d1aaa4/model_selection.py#L229) with `confidence_model` set to 'gaussian'. But when I run `estimate_flow_and_confidence_map` with a pair of images I get an error:

```python
File /src/external/DenseMatching/models/PDCNet/base_pdcnet.py:725, in ProbabilisticGLU.compute_flow_and_uncertainty(self, source_img, target_img, source_img_256, target_img_256, output_shape, inference_parameters, ratio_x, ratio_y, list_item)
    722     weight_map = torch.nn.functional.interpolate(input=uncertainty_list[1][list_item], size=output_shape,
    723                                                  mode='bilinear', align_corners=False)
    724 else:
--> 725     log_var_map = torch.nn.functional.interpolate(input=uncertainty_list[0], size=output_shape,
    726                                                   mode='bilinear', align_corners=False)
    727     weight_map = torch.nn.functional.interpolate(input=uncertainty_list[1], size=output_shape,
    728                                                  mode='bilinear', align_corners=False)
    729 p_r = estimate_probability_of_confidence_interval_of_mixture_density(weight_map, log_var_map,
    730                                                                      R=inference_parameters['R'],
    731                                                                      gaussian=inference_parameters['c_model']=='gaussian')

ValueError: Input and output must have the same number of spatial dimensions, but got input with with spatial dimensions of [256] and output size of (1024, 1024). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.

```

**Comment by brdav** [comment]
Hi, that fork is unfortunately incomplete: We originally planned to merge it into the DenseMatching repo and provide pretrained models on there as well, but so far haven't had the time to do that. 
In the case above, I think [select_model](https://github.com/brdav/DenseMatching/blob/05bca868c3278e973800a9f93a03480d93d1aaa4/model_selection.py#L49) has to be extended to create a UAWarpC model with the same arguments as used [here](https://github.com/brdav/DenseMatching/blob/05bca868c3278e973800a9f93a03480d93d1aaa4/train_settings/UAWarpC/train_UAWarpC_PDCNet_stage1.py#L100).
That being said, I'm not 100% sure if the pretrained model of the refign repo can be used for inference in the DenseMatching repo, as there might be some small differences which could hamper performance.

**Comment by scott-vsi** [comment]
That is indeed what I tried. Thanks for the reply!

**Comment by brdav** [comment]
FYI: UAWarpC has now been integrated into the [DenseMatching](https://github.com/PruneTruong/DenseMatching) repo!

**Comment by scott-vsi** [comment]
Cool. Thanks! I'll check it out
