### ISSUE TITLE
final model with the deeplabv2

### ISSUE THREAD

**Issue by wanderHZ** [brdav/refign#4]
Hi, this is a very good job!
Can you provide the final model with the deeplabv2?

**Comment by brdav** [comment]
Hi, I'm not planning on uploading the deeplabv2 models but they can be obtained with this training code (e.g. for ACDC):
```bash
python tools/run.py fit --config configs/cityscapes_acdc/refign_deeplabv2.yaml --trainer.gpus 1 --trainer.precision 16
```
You should get similar results as in Table D-5 of the arXiv version.
