### ISSUE TITLE
The download link for megadepth has expired

### ISSUE THREAD

**Issue by BruceLin30** [brdav/refign#6]

**Comment by brdav** [comment]
Thanks.

**Comment by BruceLin30** [comment]
Megadepth dataset and sfm models shared are of a heavy size and failed to download. I would be glad if you could spare a little time and provide preprocessed dataset of MegaDepth

**Comment by brdav** [comment]
Unfortunately, I currently can't host a dataset of that size on my end. You will have to try through the original download link.
