### ISSUE TITLE
question about color_preds

### ISSUE THREAD

**Issue by chenyang126** [brdav/refign#8]
Dear professor:
Sorry to bother you again. I have reproduced your work, but when i running
python tools/run.py test --config configs/cityscapes_acdc/refign_hrda_star.yaml --ckpt_path /path/to/trained/model --trainer.gpus 1 
it only outputs the value of test iou.
You have given the Predictions  on ACDC value, but I want to modify some parameters to output my own Predictions  on ACDC value. How can I see the color_pred?
best regards

**Comment by brdav** [comment]
Hello,
just change the "test" in your command to "predict" and it will save the predictions to the disk:
python tools/run.py predict --config configs/cityscapes_acdc/refign_hrda_star.yaml --ckpt_path /path/to/trained/model --trainer.gpus 1
If you want those predictions to be on the ACDC validation set, you will also have to set the parameter "predict_on" (just search for it in the config file) to "val".

**Comment by chenyang126** [comment]
<html>
<body>


- class_path: data_modules.transforms.Normalize
--
58 | predict:
59 | ACDC:
60 | predict_on: test
61 | load_keys:
62 | - image


</body>
</html>
Can I change the ''test'' in line 60 to ''val'', so it will work?

**Comment by brdav** [comment]
Yes, exactly.
